site_name: Splink
use_directory_urls: false
repo_url: https://github.com/moj-analytical-services/splink
theme:
  name: "material"
  features:
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
  logo: "img/favicon.ico"
  favicon: "img/favicon.ico"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - search
  - semiliterate
  - mknotebooks
  - tags
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      custom_templates: templates
markdown_extensions:
  - abbr
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - toc:
      permalink: True
nav:
  - Home: "README.md"
  - Topic Guide:
      - Splink's SQL backends - Spark, DuckDB etc: "topic_guides/backends.md"
      - Blocking rules for prediction vs estimation: "topic_guides/blocking_rules.md"
      - Link type - linkings vs deduping: "topic_guides/link_type.md"
      - Defining and customising comparisons: "topic_guides/customising_comparisons.ipynb"
      - Run times, performance and linking large data: "topic_guides/drivers_of_performance.md"
      - Optimising Spark performance: "topic_guides/optimising_spark.md"
      - Salting blocking rules: "topic_guides/salting.md"
  - API Reference:
      - Linker API:
          - Full API: "linker.md"
          - Exploratory analysis: "linkerexp.md"
          - Estimating model parameters: "linkerest.md"
          - Predicting results: "linkerpred.md"
          - Visualisation and quality assurance: "linkerqa.md"
      - EM Training Session API: "em_training_session.md"
      - SplinkDataFrame API: "SplinkDataFrame.md"
      - Comparisons API:
          - Comparison: "comparison.md"
          - Comparison Level: "comparison_level.md"
      - Comparisons Library API:
          - Comparison Library: "comparison_library.md"
          - Comparison Level Library: "comparison_level_library.md"
  - Settings Editor: "settingseditor/editor.md"
  - Settings dictionary reference: "settings_dict_guide.md"
  - Tutorials:
      - 0. Tutorial introduction: "demos/00_Tutorial_Introduction.ipynb"
      - 1. Exploratory analysis: "demos/01_Exploratory_analysis.ipynb"
      - 2. Estimating model parameters: "demos/02_Estimating_model_parameters.ipynb"
      - 3. Predicting results: "demos/03_Predicting_results.ipynb"
      - 4. Visualising predictions: "demos/04_Visualising_predictions.ipynb"
      - 5. Quality assurance: "demos/05_Quality_assurance.ipynb"
      - real time record linkage: "demos/real_time_record_linkage.ipynb"
      - deduplicate 50k rows of synthetic data: "demos/deduplicate_50k_synthetic.ipynb"
  - Developers' guides:
      - Caching and pipelining: "dev_guides/caching.md"
      - Understanding and debugging Splink: "dev_guides/debug_modes.md"
      - Spark caching: "dev_guides/spark_pipelining_and_caching.md"
extra_css:
- css/custom.css