[tool.poetry]
name = "splink"
version = "3.1.0"
description = "Fast probabilistic data linkage at scale"
authors = ["Robin Linacre <robinlinacre@hotmail.com>", "Sam Lindsay", "Theodore Manassis", "Tom Hepworth"]
license = "MIT"
homepage = "https://github.com/moj-analytical-services/splink"
repository = "https://github.com/moj-analytical-services/splink"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
jsonschema = "^3.2"
pandas = "^1.0.0"
duckdb = "^0.4.0"
sqlglot = "^4.0.0"
altair = "^4.2.0"
Jinja2 = "^3.0.3"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-benchmark = "^3.4.1"
tabulate = "0.8.9"
lzstring = "1.0.4"
black = "^22.1.0"
flake8 = "^4.0.1"
pyarrow = "^7.0.0"
networkx = "2.5.1"
pyspark = "^3.2.1"
rapidfuzz = "^2.0.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[flake8]
max-line-length = 88
extend-ignore = ["E203"]
